### ISSUE TITLE
Support UDH with 2 byte CSMS reference number

### ISSUE THREAD

**Issue by lillem4n** [larvit/larvitsmpp#1]
See http://en.wikipedia.org/wiki/Concatenated_SMS for a little bit more information about this.

Now this library will choke if someone is sending UDHs for esm_class 0x40 that is not 5 bytes.

**Comment by qasimakhan** [comment]
I have fixed it locally. I can push the required fixes if you want...

**Comment by lillem4n** [comment]
If you'd give me a pull request on that it would be awesome! Thank you!

**Comment by qasimakhan** [comment]
I am new to git and commits so please check if i did it right.

**Comment by lillem4n** [comment]
Thank you! I'll look into this pull request as soon as I have a chance. (Probably after the weekend :)

**Comment by qasimakhan** [comment]
Wait don't commit yet there is another bug i have to remove. During encoding and decoding the message UDH header values are changed specifically CSMS reference number. We will have to store the original buffer in PDU in order to extract accurate UDH header.

**Comment by lillem4n** [comment]
Cool cool, its great that you're working to fix the bugs!

For each bug you find, pretty please make a test to show the error, so we do not build the bug back again in a future commit.

**Comment by qasimakhan** [comment]
Hi i have made some fixes. Sorry i dont have any idea how to write tests. Maybe guide me or i can help you setup a scenario.

**Comment by lillem4n** [comment]
Goodie! :)

The first step is to run the already existing tests and make sure they all passes. After that you could write your own tests. It is quite easy once you know where to start, and it is quite fun as well. :D 

The tests is written for "mocha" https://mochajs.org/ and it can be installd with a simple "npm i -g mocha" or maybe if you need sudo to install globally "sudo npm i -g mocha"

After that, simply run "mocha" when your working directory is the base of this repository.

Everytime you do a pull request to larvit/larvitsmpp Travis will build and test it automatically: https://travis-ci.org/larvit/larvitsmpp - there you can verify that your pull request is not breaking anything we have previous tests for.

Once you've mastered running tests, you have the easiest steps left. Have a look in the "test" folder in the repo. All files there are ran by mocha. Look at how they are written and I think you can write a very simple test yourself. :)

Please just ask if you want any help or guidance. I'll answer as fast as I can. Thank you a lot for the effort so far!

**Comment by lillem4n** [comment]
With great help from @qasimakhan this bug is now closed. :)
