### ISSUE TITLE
Auto Restart

### ISSUE THREAD

**Issue by gitteraz** [larvit/larvitsmpp#43]
Hi,

Thank you for your Library. This is more of a question.

How do i configure the instance to reconnect automatically in case of a connection error in production.

Thanks in advance

**Comment by lillem4n** [comment]
Hi! Oh, that is a tricky question.

I'd catch the error and if one occurs, restart the app.

When implementing this, I'm using a queue handler to feed the messages, so the queue handler is responsible for knowing when the message really was sent (from the callback). That way it is safe to restart the application in case of a connection error. Worst case a message gets double sent.

**Comment by gitteraz** [comment]
Thank you for your answer. Will follow that path
